kind: Deployment
apiVersion: apps/v1
metadata:
  name: uber-backend
spec:
  selector:
    matchLabels:
      app: uber-backend
  template:
    metadata:
      labels:
        app: uber-backend
    spec:
      containers:
      - name: backend
        image: ankitmori1626/uber-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://admin:password123@mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: uber-backend
